name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
        rails: ['7.0', '7.1', '7.2', '8.0', 'edge']
        exclude:
          - ruby: '2.7'
            rails: '7.2'
          - ruby: '2.7'
            rails: '8.0'
          - ruby: '2.7'
            rails: 'edge'
          - ruby: '3.0'
            rails: '7.2'
          - ruby: '3.0'
            rails: '8.0'
          - ruby: '3.0'
            rails: 'edge'
          - ruby: '3.1'
            rails: '8.0'
          - ruby: '3.1'
            rails: 'edge'
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Ruby Tests
        run: bundle exec rake
